27 frontend fix sidebar layout
CPSECapstone/JAM_Q2S pull request #36
Opened 2024-03-05 18:39 UTC by Mitashi-11

This branch adds functionality to the star and favorite buttons.

2024-03-07 23:39 UTC, jluna28 requested changes

2024-03-07 23:39 UTC, jluna28 commented on src/frontend/src/Components/EditBar.css
> +    margin-left: 0;
remove since not needed

2024-03-07 23:39 UTC, jluna28 commented on src/frontend/src/Components/EditBar.css
>      margin-right: 0;
remove since not needed

2024-03-07 23:39 UTC, jluna28 commented on src/frontend/src/Components/SideBar.tsx
> +interface flowchartProps{
should be with the other interfaces

2024-03-07 23:39 UTC, jluna28 commented on src/frontend/src/Components/SideBarItem.tsx
> +interface SideBarItemProps {
should be with other interfaces

2024-03-07 23:39 UTC, jluna28 commented on src/frontend/src/Components/SideBarItem.tsx
> +            <span className="barItemTitle" onClick={clickEvent}>
check if this is needed

2024-03-08 00:06 UTC, Mitashi-11 commented on src/frontend/src/Components/SideBarItem.tsx
> +            <span className="barItemTitle" onClick={clickEvent}>
Yes, the text class overrides some of the inbuilt style of the <p>. The barItemTitle sets the layout the buttons w.r.t to the text.

2024-03-11 02:26 UTC, jluna28 approved these changes

2024-03-14 05:17 UTC, merged