37 frontend display total units
CPSECapstone/JAM_Q2S pull request #38
Opened 2024-03-08 00:50 UTC by jluna28

2024-03-08 01:24 UTC, Mitashi-11 requested changes

2024-03-08 01:24 UTC, Mitashi-11 commented on src/frontend/src/Components/Grid.tsx
> +                  {index === flowchart.length - 1 && (
This adds the total units at the end of the last term. Could it be moved to another layer on top of the last term or some other spot on the screen?

2024-03-08 01:24 UTC, Mitashi-11 commented on src/frontend/src/Components/Grid.tsx
>                  await axios.get('http://localhost:8080/get/QuarterClass/' + flowchartClass.id);
Is there a more efficient way to do this? The await inside the promise.all might be ineffective when there are many promises.

2024-03-09 03:13 UTC, jluna28 commented on src/frontend/src/Components/Grid.tsx
> +                  {index === flowchart.length - 1 && (
done

2024-03-09 03:14 UTC, jluna28 commented on src/frontend/src/Components/Grid.tsx
>                  await axios.get('http://localhost:8080/get/QuarterClass/' + flowchartClass.id);
await Promise.all was not part of this PR, will make another issue to address

2024-03-11 03:06 UTC, Mitashi-11 approved these changes

2024-03-14 15:58 UTC, merged